[package]
name = "rust-video-player"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { package = "gtk4", version = "0.9.4" }
gio = "0.20.6"
glib = "0.15"
gstreamer = "0.23"
gstreamer-video = "0.23"
gstgtk4 = { package = "gst-plugin-gtk4", version = "0.13.3"}

